SELECT SYSDATE AS DTREF,
       SUM(CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC ELSE LAN.VLRLANC * -1 END) AS VLRLANC,
       CUS.AD_SKJV2,
       CUS.NROUNICOBP,
       CASE WHEN CUS.AD_CATEGORIA = 'M' THEN 'S' ELSE 'N' END AS ANALISE_CR_M,
       CASE WHEN CUS.AD_CATEGORIA = 'U' THEN 'S' ELSE 'N' END AS ANALISE_CR_U,
       PLA.CTACTB,
       LAN.CODCENCUS,
       LAN.REFERENCIA,
       CUS.AD_CATEGORIA,
       LAN.CODPROJ,
       DECODE(PRJ.SKJV, 'M', 'S', PRJ.SKJV) AS SKJV,
       LAN.CODEMP,
       (SELECT STATUS FROM AD_UNIDADESBPS WHERE NROUNICO = CUS.NROUNICOBP) AS STATUS,
       C.CODDIRETORIA,
       C.DIRETORIA,
       CR.CR_NOVO
  FROM TCBLAN LAN,
       TCBPLA PLA,
       TSICUS CUS,
       TCSPRJ PRJ,
       VSICUS_COMP C,
       DEPARACR CR
 WHERE CUS.CODCENCUS = LAN.CODCENCUS
   AND PLA.CODCTACTB = LAN.CODCTACTB
   AND LAN.CODPROJ = PRJ.CODPROJ
   AND C.CODCENCUS = CUS.CODCENCUS
   AND CR.CODCENCUS = C.CODCENCUS
   /*AND LAN.CODEMP IN (SELECT CODEMP FROM TSIEMP WHERE AD_EMPGRUPO = 'S') SERÃO CONSIDERADAS EMPRESAS TERCEIRAS TAMBÉM - Retirado dia 09/06/2020 SAMANTA.CARVALHO*/
   AND LAN.NUMLOTE <> 9999
   AND PLA.CTACTB >= '3'
 GROUP BY CUS.AD_SKJV2,
          CUS.NROUNICOBP,
          PLA.CTACTB,
          LAN.CODCENCUS,
          LAN.REFERENCIA,
          CUS.AD_CATEGORIA,
          LAN.CODPROJ,
          DECODE(PRJ.SKJV, 'M', 'S', PRJ.SKJV),
          LAN.CODEMP,
          C.CODDIRETORIA,
          C.DIRETORIA,
          CR.CR_NOVO