CREATE OR REPLACE PROCEDURE STP_CARGA_DRE_CAIXA IS
  V_EXECINI     DATE;
  V_CODLOG      NUMBER := 0;
  V_OBS         VARCHAR2(4000);
  V_EXISTE_TB_1 NUMBER := 0;
  V_EXISTE_TB_2 NUMBER := 0;
  V_EXISTE_TB_3 NUMBER := 0;
  V_EXISTE_TB_4 NUMBER := 0;

BEGIN
  V_EXECINI := SYSDATE;

  SELECT CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE TABLE_NAME LIKE 'TB_TEMP_1') THEN 1 ELSE 0 END
       , CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE TABLE_NAME LIKE 'TB_TEMP_2') THEN 1 ELSE 0 END
       , CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE TABLE_NAME LIKE 'TB_TEMP_3') THEN 1 ELSE 0 END
       , CASE WHEN EXISTS (SELECT 1 FROM ALL_TABLES WHERE TABLE_NAME LIKE 'TB_TEMP_4') THEN 1 ELSE 0 END
  INTO V_EXISTE_TB_1
     , V_EXISTE_TB_2
     , V_EXISTE_TB_3
     , V_EXISTE_TB_4
  FROM DUAL;

  --- DROPA TEMPORARIAS
  IF V_EXISTE_TB_1 = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_1'; END IF;
  IF V_EXISTE_TB_2 = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_2'; END IF;
  IF V_EXISTE_TB_3 = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_3'; END IF;
  IF V_EXISTE_TB_4 = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_4'; END IF;

  EXECUTE IMMEDIATE 
    'CREATE TABLE TB_TEMP_1 AS
      SELECT TRUNC(FIN.DTVENC) AS DTREF
           , FIN.NUFIN
           , FIN.CODEMP
           , (SELECT NOMEFANTASIA FROM TSIEMP WHERE CODEMP = FIN.CODEMP) AS RAZAOSOCIAL
           , TRUNC(FIN.CODNAT,-2) AS CODNATPAI
           , (SELECT DESCRNAT FROM TGFNAT WHERE CODNAT = TRUNC(FIN.CODNAT,-2)) AS DESCRNATPAI
           , FIN.CODNAT
           , NAT.DESCRNAT
           , FIN.CODPARC
           , (SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = FIN.CODPARC) AS NOMEPARC
           , FIN.PROVISAO
           , FIN.RECDESP
           , FIN.DTVENC
           , FIN.DTBAIXA
           , FIN.HISTORICO
           , CAST('''' AS INT) AS NUNOTA
           , VLRDESDOB * RECDESP AS VALOR
           , CASE WHEN RECDESP = 1  THEN 1 WHEN RECDESP = -1 THEN 0 END AS COD_TIPO
           , C.AD_CATEGORIA
           , C.NROUNICOBP
           , CR.CR_NOVO AS CODCENCUS
           , CASE WHEN C.AD_CATEGORIA = ''M'' THEN ''M''
                  WHEN C.AD_CATEGORIA = ''I'' THEN ''I''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''E'' THEN ''E''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''R'' THEN ''R''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''P'' THEN ''P''
                  WHEN UNI.STATUS = ''O'' AND UNI.NROUNICO NOT IN (24,25) THEN ''O''
             END AS ANALISE
           , CAST(NAT.AD_CATEGORIA AS NUMBER) AS CATNAT
           , C.DIRETORIA
        FROM VGFFINRAT FIN
             INNER JOIN VSICUS_COMP C ON FIN.CODCENCUS = C.CODCENCUS
             INNER JOIN DEPARACR CR ON CR.CODCENCUS = C.CODCENCUS
             INNER JOIN AD_UNIDADESBPS UNI ON UNI.NROUNICO = C.NROUNICOBP
             INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
       WHERE FIN.DTBAIXA IS NULL
         AND RECDESP != 0
         AND ((PROVISAO = ''N'' 
          OR (PROVISAO = ''S'' AND (TRUNC(FIN.CODNAT,-2) NOT IN (110400,110500) OR FIN.CODNAT IN (110512,110509) )))
          OR RECDESP = -1)';

  EXECUTE IMMEDIATE
    'CREATE TABLE TB_TEMP_2 AS
      SELECT TRUNC(FIN.DTBAIXA) AS DTREF
           , FIN.NUFIN
           , FIN.CODEMP
           , (SELECT NOMEFANTASIA FROM TSIEMP WHERE CODEMP = FIN.CODEMP) AS RAZAOSOCIAL
           , TRUNC(FIN.CODNAT,-2) AS CODNATPAI
           , (SELECT DESCRNAT FROM TGFNAT WHERE CODNAT = TRUNC(FIN.CODNAT,-2)) AS DESCRNATPAI
           , FIN.CODNAT
           , NAT.DESCRNAT
           , FIN.CODPARC
           , (SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = FIN.CODPARC) AS NOMEPARC
           , FIN.PROVISAO
           , FIN.RECDESP
           , FIN.DTVENC
           , FIN.DTBAIXA
           , FIN.HISTORICO
           , CAST('''' AS INT) AS NUNOTA
           , VLRBAIXA * RECDESP AS VALOR
           , CASE WHEN RECDESP = 1  THEN 5 WHEN RECDESP = -1 THEN 4 END AS COD_TIPO 
           , C.AD_CATEGORIA
           , C.NROUNICOBP
           , CR.CR_NOVO AS CODCENCUS
           , CASE WHEN C.AD_CATEGORIA = ''M'' THEN ''M''
                  WHEN C.AD_CATEGORIA = ''I'' THEN ''I''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''E'' THEN ''E''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''R'' THEN ''R''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''P'' THEN ''P''
                  WHEN UNI.STATUS = ''O'' AND UNI.NROUNICO NOT IN (24,25) THEN ''O''
             END AS ANALISE
           , CAST(NAT.AD_CATEGORIA AS NUMBER) AS CATNAT
           , C.DIRETORIA
        FROM VGFFINRAT FIN
             INNER JOIN VSICUS_COMP C ON FIN.CODCENCUS = C.CODCENCUS
             INNER JOIN DEPARACR CR ON CR.CODCENCUS = C.CODCENCUS
             INNER JOIN AD_UNIDADESBPS UNI ON UNI.NROUNICO = C.NROUNICOBP
             INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
       WHERE FIN.PROVISAO = ''N''
         AND RECDESP != 0';

  EXECUTE IMMEDIATE
    'CREATE TABLE TB_TEMP_3 AS
      SELECT TRUNC(FAT.DTVENC) AS DTREF
           , FAT.NUFIN
           , FAT.CODEMP
           , (SELECT NOMEFANTASIA FROM TSIEMP WHERE CODEMP = FAT.CODEMP) AS RAZAOSOCIAL
           , TRUNC(FAT.CODNAT,-2) AS CODNATPAI
           , (SELECT DESCRNAT FROM TGFNAT WHERE CODNAT = TRUNC(FAT.CODNAT,-2)) AS DESCRNATPAI
           , FAT.CODNAT
           , NAT.DESCRNAT
           , FAT.CODPARC
           , (SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = FAT.CODPARC) AS NOMEPARC
           , FAT.PROVISAO
           , FAT.RECDESP
           , FAT.DTVENC
           , FAT.DTBAIXA
           , FAT.HISTORICO
           , CAST('''' AS INT) AS NUNOTA
           , FAT.VLRDESDOB AS VALOR
           , 2 AS COD_TIPO
           , C.AD_CATEGORIA
           , C.NROUNICOBP
           , CR.CR_NOVO AS CODCENCUS
           , CASE WHEN C.AD_CATEGORIA = ''M'' THEN ''M''
                  WHEN C.AD_CATEGORIA = ''I'' THEN ''I''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''E'' THEN ''E''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''R'' THEN ''R''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''P'' THEN ''P''
                  WHEN UNI.STATUS = ''O'' AND UNI.NROUNICO NOT IN (24,25) THEN ''O''
             END AS ANALISE
           , CAST(NAT.AD_CATEGORIA AS NUMBER) AS CATNAT
           , C.DIRETORIA
        FROM CND_FATPEND FAT
             INNER JOIN VSICUS_COMP C ON FAT.CODCENCUS = C.CODCENCUS
             INNER JOIN DEPARACR CR ON CR.CODCENCUS = C.CODCENCUS
             INNER JOIN AD_UNIDADESBPS UNI ON UNI.NROUNICO = C.NROUNICOBP
             INNER JOIN TGFNAT NAT ON NAT.CODNAT = FAT.CODNAT
       WHERE FAT.TIPO = ''EMPREITO''';

  EXECUTE IMMEDIATE
    'CREATE TABLE TB_TEMP_4 AS
      SELECT TRUNC(LAST_DAY(FAT.DTVENC)) AS DTREF
           , FAT.NUFIN
           , FAT.CODEMP
           , (SELECT NOMEFANTASIA FROM TSIEMP WHERE CODEMP = FAT.CODEMP) AS RAZAOSOCIAL
           , TRUNC(FAT.CODNAT,-2) AS CODNATPAI
           , (SELECT DESCRNAT FROM TGFNAT WHERE CODNAT = TRUNC(FAT.CODNAT,-2)) AS DESCRNATPAI
           , FAT.CODNAT
           , NAT.DESCRNAT
           , FAT.CODPARC
           , (SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = FAT.CODPARC) AS NOMEPARC
           , FAT.PROVISAO
           , FAT.RECDESP
           , LAST_DAY(FAT.DTVENC) AS DTVENC
           , FAT.DTBAIXA
           , FAT.HISTORICO
           , FAT.NUNOTA
           , FAT.VLRNOTA AS VALOR
           , 3 AS COD_TIPO
           , C.AD_CATEGORIA
           , C.NROUNICOBP
           , CR.CR_NOVO AS CODCENCUS
           , CASE WHEN C.AD_CATEGORIA = ''M'' THEN ''M''
                  WHEN C.AD_CATEGORIA = ''I'' THEN ''I''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''E'' THEN ''E''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''R'' THEN ''R''
                  WHEN C.AD_CATEGORIA = ''U'' AND UNI.STATUS = ''P'' THEN ''P''
                  WHEN UNI.STATUS = ''O'' AND UNI.NROUNICO NOT IN (24,25) THEN ''O''
             END AS ANALISE
           , CAST(NAT.AD_CATEGORIA AS NUMBER) AS CATNAT
           , C.DIRETORIA
        FROM CND_FATPEND FAT
             INNER JOIN VSICUS_COMP C ON FAT.CODCENCUS = C.CODCENCUS
             INNER JOIN DEPARACR CR ON CR.CODCENCUS = C.CODCENCUS
             INNER JOIN AD_UNIDADESBPS UNI ON UNI.NROUNICO = C.NROUNICOBP
             INNER JOIN TGFNAT NAT ON NAT.CODNAT = FAT.CODNAT
       WHERE FAT.TIPO = ''MEDICAO''';

  EXECUTE IMMEDIATE 'TRUNCATE TABLE AD_DRECAIXA';

  EXECUTE IMMEDIATE
    'INSERT INTO AD_DRECAIXA (
      SELECT *
        FROM (
              SELECT * FROM TB_TEMP_1
              UNION ALL
              SELECT * FROM TB_TEMP_2
              UNION ALL
              SELECT * FROM TB_TEMP_3
              UNION ALL
              SELECT * FROM TB_TEMP_4
            ) A
     )';

  COMMIT;

  --- DROPA TEMPORARIAS
  EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_1';
  EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_2';
  EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_3';
  EXECUTE IMMEDIATE 'DROP TABLE TB_TEMP_4';

  SELECT MAX(CODLOG) + 1 INTO V_CODLOG FROM AD_LOGETL;
  INSERT INTO AD_LOGETL (CODLOG, DHEXEC, ROTINA, STATUS, TABELA, TEMPO_EXEC)
       VALUES (V_CODLOG, V_EXECINI, 'STP_CARGA_DRE_CAIXA', 'C', 'AD_DRECAIXA', (SYSDATE - V_EXECINI) * 24 * 60 * 60);
  COMMIT;

  EXCEPTION WHEN OTHERS THEN
    V_OBS := SQLERRM;

    SELECT MAX(CODLOG) + 1 INTO V_CODLOG FROM AD_LOGETL;
    INSERT INTO AD_LOGETL (CODLOG, DHEXEC, OBS, ROTINA, STATUS, TABELA, TEMPO_EXEC)
         VALUES (V_CODLOG, V_EXECINI, V_OBS, 'STP_CARGA_DRE_CAIXA', 'E', 'AD_DRECAIXA', (SYSDATE - V_EXECINI) * 24 * 60 * 60);
    COMMIT;

END;

/